# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(auto_now=True)),
                ('leaving_time', models.DateTimeField(auto_now=True)),
                ('parents', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sex', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('is_present', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='kid_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Kid'),
        ),
    ]
