# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('arrival', models.CharField(max_length=25)),
                ('departure', models.CharField(blank=True, max_length=25)),
                ('parents', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('photo', models.FileField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='kid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Kid'),
        ),
    ]
