# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='leaving_time',
            new_name='departure_time',
        ),
    ]
