# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20180629_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='kid_name',
            new_name='name',
        ),
    ]
