# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20180629_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='photo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
